# Random Forest Regression for predicting and ranking importance of various features

## Importing the packages and data

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
dataset = pd.read_csv('cosesamp.csv')

In [3]:
dataset.head()

,iso_code,continent,location,total_cases,total_deaths,total_cases_per_million,total_deaths_per_million,stringency_index,population,population_density,...,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,hospital_beds_per_thousand,life_expectancy,human_development_index,outdoor_pollution_death_rate,unsafe_sanitaton_death_rate
0,ALB,Europe,Albania,210224,3217,73173.975,1119.761,46.30,2872934,104.871,...,1.1,304.195,10.08,7.1,51.2,2.89,78.57,0.795,37.500046,0.007407
1,ARG,South America,Argentina,5654408,117169,123984.343,2569.168,41.67,45605823,16.177,...,0.6,191.032,5.50,16.2,27.7,5.00,76.67,0.845,24.188353,0.023629
2,AUS,Oceania,Australia,425496,2253,16499.628,87.365,40.28,25788217,3.202,...,0.5,107.791,5.07,13.0,16.5,3.84,83.44,0.944,4.307855,0.004647
3,AUT,Europe,Austria,1278619,13733,141392.107,1518.621,60.19,9043072,106.749,...,0.7,145.183,6.35,28.4,30.9,7.37,81.54,0.922,13.592954,0.008561
4,BEL,Europe,Belgium,2105343,28331,180990.591,2435.539,50.00,11632334,375.564,...,0.2,114.898,4.29,25.1,31.4,5.64,81.63,0.931,14.964949,0.012591

In [4]:
y = dataset['total_cases_per_million']
X = dataset.iloc[:, 7:]

In [5]:
X.head()

,stringency_index,population,population_density,median_age,aged_65_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,hospital_beds_per_thousand,life_expectancy,human_development_index,outdoor_pollution_death_rate,unsafe_sanitaton_death_rate
0,46.30,2872934,104.871,38.0,13.188,11803.431,1.1,304.195,10.08,7.1,51.2,2.89,78.57,0.795,37.500046,0.007407
1,41.67,45605823,16.177,31.9,11.198,18933.907,0.6,191.032,5.50,16.2,27.7,5.00,76.67,0.845,24.188353,0.023629
2,40.28,25788217,3.202,37.9,15.504,44648.710,0.5,107.791,5.07,13.0,16.5,3.84,83.44,0.944,4.307855,0.004647
3,60.19,9043072,106.749,44.4,19.202,45436.686,0.7,145.183,6.35,28.4,30.9,7.37,81.54,0.922,13.592954,0.008561
4,50.00,11632334,375.564,41.8,18.571,42658.576,0.2,114.898,4.29,25.1,31.4,5.64,81.63,0.931,14.964949,0.012591

In [6]:
y.head()

0     73173.975
1    123984.343
2     16499.628
3    141392.107
4    180990.591
Name: total_cases_per_million, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [24]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=1000, max_features=4, max_depth=7,  random_state=18, max_samples=0.5)
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

In [25]:
imp = regressor.feature_importances_
imp_percent = []
for i in imp:
    imp_percent.append(i*100)
print(imp_percent)
imp_df = np.array(imp_percent)

[1.9100426044072152, 5.755227612352758, 3.3683116291912416, 7.406129574356987, 6.731746345030469, 9.374220411918326, 5.372984353545748, 2.9765342636494747, 3.4736261479103727, 10.55007695209515, 2.3568812714353817, 7.680790142693052, 5.598145401669721, 15.206594474876493, 2.859624051800213, 9.379064763067408]

In [26]:
from sklearn import metrics
np.sqrt(metrics.mean_squared_error(y_pred, y_test))

40553.776014860494